import { NextResponse } from "next/server"

export async function GET() {
  const venues = [
    {
      id: "1",
      name: "Sky Bar Pattaya",
      description: "Rooftop bar with panoramic city views and premium cocktails",
      address: "Central Festival Pattaya Beach, 25th Floor",
      category: "bars",
      image: "/placeholder.svg?height=300&width=400",
      rating: 4.6,
      reviewCount: 234,
      isOpen: true,
      hours: "6:00 PM - 2:00 AM",
      capacity: 150,
      features: ["Rooftop", "City Views", "Cocktails", "Live DJ"],
    },
    {
      id: "2",
      name: "Insomnia Nightclub",
      description: "Premier nightclub with international DJs and VIP sections",
      address: "Walking Street, South Pattaya",
      category: "clubs",
      image: "/placeholder.svg?height=300&width=400",
      rating: 4.3,
      reviewCount: 567,
      isOpen: true,
      hours: "10:00 PM - 6:00 AM",
      capacity: 800,
      features: ["VIP Sections", "International DJs", "Dance Floor", "Bottle Service"],
    },
    {
      id: "3",
      name: "Horizon Lounge",
      description: "Sophisticated lounge with craft cocktails and live music",
      address: "Hilton Pattaya, 34th Floor",
      category: "lounges",
      image: "/placeholder.svg?height=300&width=400",
      rating: 4.8,
      reviewCount: 189,
      isOpen: false,
      hours: "7:00 PM - 1:00 AM",
      capacity: 100,
      features: ["Ocean Views", "Live Music", "Craft Cocktails", "Fine Dining"],
    },
    {
      id: "4",
      name: "Mixx Discotheque",
      description: "High-energy nightclub with multiple dance floors and bars",
      address: "LK Metro, Pattaya Second Road",
      category: "clubs",
      image: "/placeholder.svg?height=300&width=400",
      rating: 4.1,
      reviewCount: 445,
      isOpen: true,
      hours: "9:00 PM - 4:00 AM",
      capacity: 1000,
      features: ["Multiple Floors", "Live Shows", "International DJs", "VIP Areas"],
    },
    {
      id: "5",
      name: "Gentlemen's Club Elite",
      description: "Upscale adult entertainment venue with professional shows",
      address: "Walking Street, Central Area",
      category: "adult",
      image: "/placeholder.svg?height=300&width=400",
      rating: 4.2,
      reviewCount: 156,
      isOpen: true,
      hours: "8:00 PM - 3:00 AM",
      capacity: 200,
      features: ["Live Shows", "VIP Rooms", "Premium Service", "Adult Entertainment"],
    },
  ]

  return NextResponse.json({ data: venues })
}
