import { NextResponse } from "next/server"

export async function GET() {
  try {
    // Simulated blog posts data - replace with actual API calls
    const blogPosts = [
      {
        id: "1",
        title: "Top 10 Hidden Beaches in Pattaya You Must Visit This Year",
        excerpt: "Discover pristine beaches away from the crowds, perfect for a peaceful day under the Thai sun.",
        author: "Sarah Johnson",
        publishedAt: "2024-01-15T10:00:00Z",
        readTime: "5 min read",
        category: "Travel",
        image: "/placeholder.svg?height=160&width=320&text=Hidden+Beaches",
        views: 2847,
        comments: 23,
        likes: 156,
        featured: true,
        trending: false,
        tags: ["beaches", "hidden gems", "travel tips"],
      },
      {
        id: "2",
        title: "Pattaya Night Markets: A Food Lover's Ultimate Guide",
        excerpt: "From street food to local delicacies, explore the vibrant night market scene in Pattaya.",
        author: "Mike Chen",
        publishedAt: "2024-01-14T18:30:00Z",
        readTime: "7 min read",
        category: "Food & Dining",
        image: "/placeholder.svg?height=160&width=320&text=Night+Markets",
        views: 1923,
        comments: 45,
        likes: 234,
        featured: false,
        trending: true,
        tags: ["food", "night markets", "local cuisine"],
      },
      {
        id: "3",
        title: "Best Time to Visit Pattaya: Weather and Seasonal Guide 2024",
        excerpt: "Plan your perfect trip with our comprehensive guide to Pattaya's weather patterns and seasons.",
        author: "Emma Wilson",
        publishedAt: "2024-01-13T14:15:00Z",
        readTime: "6 min read",
        category: "Travel Planning",
        image: "/placeholder.svg?height=160&width=320&text=Weather+Guide",
        views: 3456,
        comments: 67,
        likes: 289,
        featured: true,
        trending: true,
        tags: ["weather", "travel planning", "seasons"],
      },
      {
        id: "4",
        title: "Pattaya's Cultural Temples: A Spiritual Journey",
        excerpt: "Explore the rich spiritual heritage of Pattaya through its magnificent temples and cultural sites.",
        author: "David Kim",
        publishedAt: "2024-01-12T09:45:00Z",
        readTime: "8 min read",
        category: "Culture",
        image: "/placeholder.svg?height=160&width=320&text=Temples",
        views: 1567,
        comments: 34,
        likes: 178,
        featured: false,
        trending: false,
        tags: ["temples", "culture", "spirituality"],
      },
      {
        id: "5",
        title: "Adventure Sports in Pattaya: Thrills Beyond the Beach",
        excerpt: "From parasailing to jet skiing, discover the adrenaline-pumping activities Pattaya has to offer.",
        author: "Alex Rodriguez",
        publishedAt: "2024-01-11T16:20:00Z",
        readTime: "5 min read",
        category: "Adventure",
        image: "/placeholder.svg?height=160&width=320&text=Adventure+Sports",
        views: 2134,
        comments: 56,
        likes: 267,
        featured: false,
        trending: true,
        tags: ["adventure", "water sports", "activities"],
      },
      {
        id: "6",
        title: "Pattaya Shopping Guide: From Malls to Local Markets",
        excerpt: "Your complete guide to shopping in Pattaya, from luxury malls to authentic local markets.",
        author: "Lisa Thompson",
        publishedAt: "2024-01-10T12:00:00Z",
        readTime: "6 min read",
        category: "Shopping",
        image: "/placeholder.svg?height=160&width=320&text=Shopping+Guide",
        views: 1789,
        comments: 29,
        likes: 145,
        featured: false,
        trending: false,
        tags: ["shopping", "malls", "markets"],
      },
      {
        id: "7",
        title: "Family-Friendly Activities in Pattaya: Fun for All Ages",
        excerpt: "Discover the best family attractions and activities that will keep everyone entertained.",
        author: "Jennifer Lee",
        publishedAt: "2024-01-09T11:30:00Z",
        readTime: "7 min read",
        category: "Family",
        image: "/placeholder.svg?height=160&width=320&text=Family+Fun",
        views: 2456,
        comments: 78,
        likes: 312,
        featured: true,
        trending: false,
        tags: ["family", "kids", "attractions"],
      },
      {
        id: "8",
        title: "Pattaya Transportation Guide: Getting Around Like a Local",
        excerpt: "Master the art of getting around Pattaya with our comprehensive transportation guide.",
        author: "Tom Anderson",
        publishedAt: "2024-01-08T15:45:00Z",
        readTime: "4 min read",
        category: "Transportation",
        image: "/placeholder.svg?height=160&width=320&text=Transportation",
        views: 1345,
        comments: 23,
        likes: 89,
        featured: false,
        trending: false,
        tags: ["transportation", "local tips", "getting around"],
      },
      {
        id: "9",
        title: "Luxury Resorts in Pattaya: Where to Stay for Ultimate Comfort",
        excerpt: "Indulge in luxury with our curated selection of Pattaya's finest resorts and hotels.",
        author: "Rachel Green",
        publishedAt: "2024-01-07T13:20:00Z",
        readTime: "6 min read",
        category: "Accommodation",
        image: "/placeholder.svg?height=160&width=320&text=Luxury+Resorts",
        views: 1876,
        comments: 41,
        likes: 198,
        featured: false,
        trending: false,
        tags: ["luxury", "resorts", "accommodation"],
      },
      {
        id: "10",
        title: "Pattaya Festivals and Events Calendar 2024",
        excerpt: "Don't miss out on the exciting festivals and events happening in Pattaya throughout the year.",
        author: "Mark Davis",
        publishedAt: "2024-01-06T10:15:00Z",
        readTime: "5 min read",
        category: "Events",
        image: "/placeholder.svg?height=160&width=320&text=Festivals",
        views: 2234,
        comments: 52,
        likes: 276,
        featured: false,
        trending: true,
        tags: ["festivals", "events", "calendar"],
      },
      {
        id: "11",
        title: "Sustainable Tourism in Pattaya: Travel Responsibly",
        excerpt:
          "Learn how to enjoy Pattaya while minimizing your environmental impact and supporting local communities.",
        author: "Green Travel Team",
        publishedAt: "2024-01-05T14:30:00Z",
        readTime: "8 min read",
        category: "Sustainable Travel",
        image: "/placeholder.svg?height=160&width=320&text=Sustainable+Tourism",
        views: 1123,
        comments: 34,
        likes: 167,
        featured: true,
        trending: false,
        tags: ["sustainability", "eco-tourism", "responsible travel"],
      },
      {
        id: "12",
        title: "Pattaya's Art Scene: Galleries, Studios, and Street Art",
        excerpt: "Explore the vibrant art culture of Pattaya, from contemporary galleries to stunning street murals.",
        author: "Art Enthusiast",
        publishedAt: "2024-01-04T16:45:00Z",
        readTime: "6 min read",
        category: "Arts & Culture",
        image: "/placeholder.svg?height=160&width=320&text=Art+Scene",
        views: 987,
        comments: 19,
        likes: 134,
        featured: false,
        trending: false,
        tags: ["art", "galleries", "culture"],
      },
      {
        id: "13",
        title: "Digital Nomad's Guide to Working from Pattaya",
        excerpt: "Everything you need to know about living and working remotely in this tropical paradise.",
        author: "Remote Worker",
        publishedAt: "2024-01-03T09:00:00Z",
        readTime: "7 min read",
        category: "Digital Nomad",
        image: "/placeholder.svg?height=160&width=320&text=Digital+Nomad",
        views: 1567,
        comments: 43,
        likes: 201,
        featured: false,
        trending: true,
        tags: ["digital nomad", "remote work", "coworking"],
      },
      {
        id: "14",
        title: "Pattaya's Wellness Scene: Spas, Yoga, and Meditation",
        excerpt: "Rejuvenate your mind and body with Pattaya's extensive wellness and spa offerings.",
        author: "Wellness Guru",
        publishedAt: "2024-01-02T11:30:00Z",
        readTime: "5 min read",
        category: "Wellness",
        image: "/placeholder.svg?height=160&width=320&text=Wellness",
        views: 1789,
        comments: 37,
        likes: 223,
        featured: false,
        trending: false,
        tags: ["wellness", "spa", "meditation"],
      },
      {
        id: "15",
        title: "New Year Celebrations in Pattaya: Ring in 2024 in Style",
        excerpt: "Discover the best places and events to celebrate New Year's Eve in Pattaya.",
        author: "Party Planner",
        publishedAt: "2024-01-01T20:00:00Z",
        readTime: "4 min read",
        category: "Events",
        image: "/placeholder.svg?height=160&width=320&text=New+Year",
        views: 3456,
        comments: 89,
        likes: 445,
        featured: true,
        trending: true,
        tags: ["new year", "celebrations", "parties"],
      },
    ]

    return NextResponse.json(blogPosts)
  } catch (error) {
    console.error("Error fetching blog posts:", error)
    return NextResponse.json({ error: "Failed to fetch blog posts" }, { status: 500 })
  }
}
